### ISSUE TITLE
Fix: 手機版 Menu style

### ISSUE THREAD

**Issue by ellallu0903** [ChillKa/chillka-frontend#107]
1. 「登出」介面在手機版有偏移，每個 item 的間距可以再調整一下
> 想確認間距調整是再調小嗎？目前是 margin-bottom: 16px（同設計稿），我試過改成 12px 感覺會有點窄，下面留白會變多

2. 手機版打開popover 會閃爍一下，但我猜這個不好修，先這樣。
> 應該是原本使用 dialog 元件的問題（Pending）

_Originally posted by @blp100 in https://github.com/ChillKa/chillka-frontend/pull/103#pullrequestreview-2156915777_

**Comment by blp100** [comment]
抱歉，是我說明得不夠清楚，主要是選單各元素的間距太小了，可以參考figma

ref: https://www.figma.com/design/6JPbEOj0WIGCAr3gJQU0Cb/%E5%85%AD%E8%A7%92_ChillKa?node-id=285-5861&t=fLIn20qEgfvtFWwx-4
