### ISSUE TITLE
Bug: Ticket inquiry Information Mismatch

### ISSUE THREAD

**Issue by ellallu0903** [ChillKa/chillka-frontend#149]
@zim314 
1. 更正訂單編號
2. 更正數量
3. 更正主辦方顯示
4. 若票券無使用期限，應顯示「無期限」
5. 付款方式需確認顯示內容
6. 「取消活動」按鈕應 `disabled`
7. 列表的使用期限，同第四點
8. 列表的「已使用或過期」狀態之活動名稱，應該是 `[ticket.activity.name] | [ticket.ticket.name]`
9.  列表的「已使用或過期」狀態內的「使用票券」應 `disabled`
10. 列表的「可使用」但票券狀態為「待付款」QRcode 可以點開，應 `disabled`
11. 承上，「待付款」可重新至付款頁面嗎？
![截圖 2024-07-12 上午10 45 36](https://github.com/user-attachments/assets/7328447f-3be7-4374-8b36-fd5a84cf9b59)
![image](https://github.com/user-attachments/assets/875173b1-3baf-4a8e-8ad5-dd0cf48a979b)

**Comment by zim314** [comment]
以解決
